// Generated automatically by prepareDemo.ts — DO NOT EDIT DIRECTLY
import type { Photo } from '@christmas-games/platform';

export const publicDemoPhotos: readonly Photo[] = [
  {
    id: 'demo_001',
    width: 1448,
    height: 1086,
    aspectRatio: 1.3333,
    orientation: 'landscape',
    variants: {
      thumb: '/fixtures/demo/demo_001/thumb.webp',
      card: '/fixtures/demo/demo_001/card.webp',
      game: '/fixtures/demo/demo_001/game.webp',
    },
  },
  {
    id: 'demo_002',
    width: 1448,
    height: 1086,
    aspectRatio: 1.3333,
    orientation: 'landscape',
    variants: {
      thumb: '/fixtures/demo/demo_002/thumb.webp',
      card: '/fixtures/demo/demo_002/card.webp',
      game: '/fixtures/demo/demo_002/game.webp',
    },
  },
  {
    id: 'demo_003',
    width: 5600,
    height: 4000,
    aspectRatio: 1.4,
    orientation: 'landscape',
    variants: {
      thumb: '/fixtures/demo/demo_003/thumb.webp',
      card: '/fixtures/demo/demo_003/card.webp',
      game: '/fixtures/demo/demo_003/game.webp',
    },
  },
  {
    id: 'demo_004',
    width: 1484,
    height: 1060,
    aspectRatio: 1.4,
    orientation: 'landscape',
    variants: {
      thumb: '/fixtures/demo/demo_004/thumb.webp',
      card: '/fixtures/demo/demo_004/card.webp',
      game: '/fixtures/demo/demo_004/game.webp',
    },
  },
  {
    id: 'demo_005',
    width: 1060,
    height: 1484,
    aspectRatio: 0.7143,
    orientation: 'portrait',
    variants: {
      thumb: '/fixtures/demo/demo_005/thumb.webp',
      card: '/fixtures/demo/demo_005/card.webp',
      game: '/fixtures/demo/demo_005/game.webp',
    },
  },
  {
    id: 'demo_006',
    width: 1484,
    height: 1060,
    aspectRatio: 1.4,
    orientation: 'landscape',
    variants: {
      thumb: '/fixtures/demo/demo_006/thumb.webp',
      card: '/fixtures/demo/demo_006/card.webp',
      game: '/fixtures/demo/demo_006/game.webp',
    },
  },
  {
    id: 'demo_007',
    width: 1484,
    height: 1060,
    aspectRatio: 1.4,
    orientation: 'landscape',
    variants: {
      thumb: '/fixtures/demo/demo_007/thumb.webp',
      card: '/fixtures/demo/demo_007/card.webp',
      game: '/fixtures/demo/demo_007/game.webp',
    },
  },
  {
    id: 'demo_008',
    width: 1060,
    height: 1484,
    aspectRatio: 0.7143,
    orientation: 'portrait',
    variants: {
      thumb: '/fixtures/demo/demo_008/thumb.webp',
      card: '/fixtures/demo/demo_008/card.webp',
      game: '/fixtures/demo/demo_008/game.webp',
    },
  },
  {
    id: 'demo_009',
    width: 1484,
    height: 1060,
    aspectRatio: 1.4,
    orientation: 'landscape',
    variants: {
      thumb: '/fixtures/demo/demo_009/thumb.webp',
      card: '/fixtures/demo/demo_009/card.webp',
      game: '/fixtures/demo/demo_009/game.webp',
    },
  },
  {
    id: 'demo_010',
    width: 1484,
    height: 1060,
    aspectRatio: 1.4,
    orientation: 'landscape',
    variants: {
      thumb: '/fixtures/demo/demo_010/thumb.webp',
      card: '/fixtures/demo/demo_010/card.webp',
      game: '/fixtures/demo/demo_010/game.webp',
    },
  },
  {
    id: 'demo_011',
    width: 1484,
    height: 1060,
    aspectRatio: 1.4,
    orientation: 'landscape',
    variants: {
      thumb: '/fixtures/demo/demo_011/thumb.webp',
      card: '/fixtures/demo/demo_011/card.webp',
      game: '/fixtures/demo/demo_011/game.webp',
    },
  },
  {
    id: 'demo_012',
    width: 1484,
    height: 1060,
    aspectRatio: 1.4,
    orientation: 'landscape',
    variants: {
      thumb: '/fixtures/demo/demo_012/thumb.webp',
      card: '/fixtures/demo/demo_012/card.webp',
      game: '/fixtures/demo/demo_012/game.webp',
    },
  },
  {
    id: 'demo_013',
    width: 2500,
    height: 1786,
    aspectRatio: 1.3998,
    orientation: 'landscape',
    variants: {
      thumb: '/fixtures/demo/demo_013/thumb.webp',
      card: '/fixtures/demo/demo_013/card.webp',
      game: '/fixtures/demo/demo_013/game.webp',
    },
  },
  {
    id: 'demo_014',
    width: 1060,
    height: 1484,
    aspectRatio: 0.7143,
    orientation: 'portrait',
    variants: {
      thumb: '/fixtures/demo/demo_014/thumb.webp',
      card: '/fixtures/demo/demo_014/card.webp',
      game: '/fixtures/demo/demo_014/game.webp',
    },
  },
  {
    id: 'demo_015',
    width: 4000,
    height: 2857,
    aspectRatio: 1.4001,
    orientation: 'landscape',
    variants: {
      thumb: '/fixtures/demo/demo_015/thumb.webp',
      card: '/fixtures/demo/demo_015/card.webp',
      game: '/fixtures/demo/demo_015/game.webp',
    },
  },
  {
    id: 'demo_016',
    width: 1484,
    height: 1060,
    aspectRatio: 1.4,
    orientation: 'landscape',
    variants: {
      thumb: '/fixtures/demo/demo_016/thumb.webp',
      card: '/fixtures/demo/demo_016/card.webp',
      game: '/fixtures/demo/demo_016/game.webp',
    },
  },
  {
    id: 'demo_017',
    width: 4806,
    height: 3433,
    aspectRatio: 1.3999,
    orientation: 'landscape',
    variants: {
      thumb: '/fixtures/demo/demo_017/thumb.webp',
      card: '/fixtures/demo/demo_017/card.webp',
      game: '/fixtures/demo/demo_017/game.webp',
    },
  },
  {
    id: 'demo_018',
    width: 5325,
    height: 3803,
    aspectRatio: 1.4002,
    orientation: 'landscape',
    variants: {
      thumb: '/fixtures/demo/demo_018/thumb.webp',
      card: '/fixtures/demo/demo_018/card.webp',
      game: '/fixtures/demo/demo_018/game.webp',
    },
  },
  {
    id: 'demo_019',
    width: 1484,
    height: 1060,
    aspectRatio: 1.4,
    orientation: 'landscape',
    variants: {
      thumb: '/fixtures/demo/demo_019/thumb.webp',
      card: '/fixtures/demo/demo_019/card.webp',
      game: '/fixtures/demo/demo_019/game.webp',
    },
  },
  {
    id: 'demo_020',
    width: 2500,
    height: 1786,
    aspectRatio: 1.3998,
    orientation: 'landscape',
    variants: {
      thumb: '/fixtures/demo/demo_020/thumb.webp',
      card: '/fixtures/demo/demo_020/card.webp',
      game: '/fixtures/demo/demo_020/game.webp',
    },
  },
  {
    id: 'demo_021',
    width: 2500,
    height: 1785,
    aspectRatio: 1.4006,
    orientation: 'landscape',
    variants: {
      thumb: '/fixtures/demo/demo_021/thumb.webp',
      card: '/fixtures/demo/demo_021/card.webp',
      game: '/fixtures/demo/demo_021/game.webp',
    },
  },
  {
    id: 'demo_022',
    width: 1485,
    height: 1059,
    aspectRatio: 1.4023,
    orientation: 'landscape',
    variants: {
      thumb: '/fixtures/demo/demo_022/thumb.webp',
      card: '/fixtures/demo/demo_022/card.webp',
      game: '/fixtures/demo/demo_022/game.webp',
    },
  },
  {
    id: 'demo_023',
    width: 5600,
    height: 4000,
    aspectRatio: 1.4,
    orientation: 'landscape',
    variants: {
      thumb: '/fixtures/demo/demo_023/thumb.webp',
      card: '/fixtures/demo/demo_023/card.webp',
      game: '/fixtures/demo/demo_023/game.webp',
    },
  },
  {
    id: 'demo_024',
    width: 1484,
    height: 1060,
    aspectRatio: 1.4,
    orientation: 'landscape',
    variants: {
      thumb: '/fixtures/demo/demo_024/thumb.webp',
      card: '/fixtures/demo/demo_024/card.webp',
      game: '/fixtures/demo/demo_024/game.webp',
    },
  },
  {
    id: 'demo_025',
    width: 2500,
    height: 1786,
    aspectRatio: 1.3998,
    orientation: 'landscape',
    variants: {
      thumb: '/fixtures/demo/demo_025/thumb.webp',
      card: '/fixtures/demo/demo_025/card.webp',
      game: '/fixtures/demo/demo_025/game.webp',
    },
  },
  {
    id: 'demo_026',
    width: 2500,
    height: 1786,
    aspectRatio: 1.3998,
    orientation: 'landscape',
    variants: {
      thumb: '/fixtures/demo/demo_026/thumb.webp',
      card: '/fixtures/demo/demo_026/card.webp',
      game: '/fixtures/demo/demo_026/game.webp',
    },
  },
  {
    id: 'demo_027',
    width: 4000,
    height: 5600,
    aspectRatio: 0.7143,
    orientation: 'portrait',
    variants: {
      thumb: '/fixtures/demo/demo_027/thumb.webp',
      card: '/fixtures/demo/demo_027/card.webp',
      game: '/fixtures/demo/demo_027/game.webp',
    },
  },
] as const;
