import { execFileSync } from 'node:child_process';
import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { format } from 'prettier';

const root = process.cwd();
// Use the same file set as a checkout, including new files awaiting a commit.
// Empty directories, private media and ignored reports must not change the map.
const files = [
  ...new Set(
    execFileSync('git', ['ls-files', '--cached', '--others', '--exclude-standard', '-z'], {
      cwd: root,
      encoding: 'utf8',
    })
      .split('\0')
      .filter(Boolean),
  ),
];
const deleted = new Set(
  execFileSync('git', ['ls-files', '--deleted', '-z'], { cwd: root, encoding: 'utf8' })
    .split('\0')
    .filter(Boolean),
);
const visibleFiles = files.filter((file) => !deleted.has(file));
const directories = new Map();
for (const file of visibleFiles) {
  let directory = directories;
  for (const part of file.split('/')) {
    if (!directory.has(part)) directory.set(part, new Map());
    directory = directory.get(part);
  }
}
const compareNames = (left, right) => (left < right ? -1 : left > right ? 1 : 0);

function tree(directory, prefix = '') {
  const visible = [...directory.entries()].sort(([left], [right]) => compareNames(left, right));
  const lines = [];
  for (const [index, [name, children]] of visible.entries()) {
    const last = index === visible.length - 1;
    lines.push(`${prefix}${last ? '└──' : '├──'} ${name}`);
    lines.push(...tree(children, `${prefix}${last ? '    ' : '│   '}`));
  }
  return lines;
}

const packageFiles = visibleFiles
  .filter((file) => /^(?:apps|packages|tools)\/.+\/package\.json$/.test(file))
  .sort(compareNames);

const packages = [];
for (const file of packageFiles) {
  const manifest = JSON.parse(await readFile(join(root, file), 'utf8'));
  const entry = manifest.exports ?? manifest.main ?? '—';
  packages.push(
    `| \`${manifest.name}\` | \`${file}\` | \`${typeof entry === 'string' ? entry : JSON.stringify(entry)}\` |`,
  );
}

const document = await format(
  `# Repository map\n\n> Generated by \`pnpm repo:map\`. Do not edit manually.\n\n## Tree\n\n\`\`\`text\n${tree(directories).join('\n')}\n\`\`\`\n\n## Package entry points\n\n| Package | Manifest | Entry |\n| --- | --- | --- |\n${packages.join('\n')}\n`,
  { filepath: 'docs/generated/repo-map.md' },
);
const target = join(root, 'docs/generated/repo-map.md');
if (process.argv.includes('--check')) {
  const current = await readFile(target, 'utf8').catch(() => '');
  if (current.replaceAll('\r\n', '\n') !== document) {
    console.error('docs/generated/repo-map.md is stale. Run pnpm repo:map.');
    process.exitCode = 1;
  }
} else {
  await writeFile(target, document, 'utf8');
}
