import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join, relative } from 'node:path';
import { format } from 'prettier';

const root = process.cwd();
const ignored = new Set([
  '.git',
  '.reference',
  'node_modules',
  'dist',
  'coverage',
  'playwright-report',
  'test-results',
]);
const ignoredPaths = new Set(['tools/fixture-generator/tests/fixtures']);

async function tree(directory, prefix = '') {
  const entries = await readdir(directory, { withFileTypes: true });
  const visible = entries
    .filter(
      (entry) =>
        !ignored.has(entry.name) &&
        !ignoredPaths.has(relative(root, join(directory, entry.name)).replaceAll('\\', '/')),
    )
    .sort((left, right) => left.name.localeCompare(right.name));
  const lines = [];
  for (const [index, entry] of visible.entries()) {
    const last = index === visible.length - 1;
    lines.push(`${prefix}${last ? '└──' : '├──'} ${entry.name}`);
    if (entry.isDirectory())
      lines.push(
        ...(await tree(join(directory, entry.name), `${prefix}${last ? '    ' : '│   '}`)),
      );
  }
  return lines;
}

const packageFiles = [
  'apps/play/package.json',
  'packages/platform/package.json',
  'packages/theme/package.json',
  'packages/games/dev-smoke/package.json',
  'packages/games/puzzle-swap/package.json',
  'packages/games/memory/package.json',
  'packages/games/tic-tac-toe/package.json',
  'tools/media-pipeline/package.json',
  'tools/fixture-generator/package.json',
];

const packages = [];
for (const file of packageFiles) {
  try {
    const manifest = JSON.parse(await readFile(join(root, file), 'utf8'));
    packages.push(
      `| \`${manifest.name}\` | \`${relative(root, join(root, file)).replaceAll('\\\\', '/')}\` | \`${manifest.exports ?? '—'}\` |`,
    );
  } catch {
    // A package may not exist in an intentionally incomplete phase.
  }
}

const document = await format(
  `# Repository map\n\n> Generated by \`pnpm repo:map\`. Do not edit manually.\n\n## Tree\n\n\`\`\`text\n${(await tree(root)).join('\n')}\n\`\`\`\n\n## Package entry points\n\n| Package | Manifest | Entry |\n| --- | --- | --- |\n${packages.join('\n')}\n`,
  { filepath: 'docs/generated/repo-map.md' },
);
const target = join(root, 'docs/generated/repo-map.md');
if (process.argv.includes('--check')) {
  const current = await readFile(target, 'utf8').catch(() => '');
  if (current !== document) {
    console.error('docs/generated/repo-map.md is stale. Run pnpm repo:map.');
    process.exitCode = 1;
  }
} else {
  await writeFile(target, document, 'utf8');
}
