// Generated by the explicit offline shell audio preparation script.
export const shellAudioAssets = {
  tap: {
    mp3: '/assets/christmas-shell/audio/tap-v1.mp3',
    m4a: '/assets/christmas-shell/audio/tap-v1.m4a',
    volume: 0.26,
  },
  toggle: {
    mp3: '/assets/christmas-shell/audio/toggle-v1.mp3',
    m4a: '/assets/christmas-shell/audio/toggle-v1.m4a',
    volume: 0.25,
  },
  magic: {
    mp3: '/assets/christmas-shell/audio/magic-v1.mp3',
    m4a: '/assets/christmas-shell/audio/magic-v1.m4a',
    volume: 0.2,
  },
  'paper-a': {
    mp3: '/assets/christmas-shell/audio/paper-a-v1.mp3',
    m4a: '/assets/christmas-shell/audio/paper-a-v1.m4a',
    volume: 0.28,
  },
  'paper-b': {
    mp3: '/assets/christmas-shell/audio/paper-b-v1.mp3',
    m4a: '/assets/christmas-shell/audio/paper-b-v1.m4a',
    volume: 0.28,
  },
  open: {
    mp3: '/assets/christmas-shell/audio/open-v1.mp3',
    m4a: '/assets/christmas-shell/audio/open-v1.m4a',
    volume: 0.26,
  },
  back: {
    mp3: '/assets/christmas-shell/audio/back-v1.mp3',
    m4a: '/assets/christmas-shell/audio/back-v1.m4a',
    volume: 0.26,
  },
  reveal: {
    mp3: '/assets/christmas-shell/audio/reveal-v1.mp3',
    m4a: '/assets/christmas-shell/audio/reveal-v1.m4a',
    volume: 0.22,
  },
  'bells-a': {
    mp3: '/assets/christmas-shell/audio/bells-a-v1.mp3',
    m4a: '/assets/christmas-shell/audio/bells-a-v1.m4a',
    volume: 0.24,
  },
  'bells-b': {
    mp3: '/assets/christmas-shell/audio/bells-b-v1.mp3',
    m4a: '/assets/christmas-shell/audio/bells-b-v1.m4a',
    volume: 0.24,
  },
  snow: {
    mp3: '/assets/christmas-shell/audio/snow-v1.mp3',
    m4a: '/assets/christmas-shell/audio/snow-v1.m4a',
    volume: 0.2,
  },
  start: {
    mp3: '/assets/christmas-shell/audio/start-v1.mp3',
    m4a: '/assets/christmas-shell/audio/start-v1.m4a',
    volume: 0.24,
  },
} as const;
